[workspace]
resolver = "2"

members = [
    "acronym",
    "anagram",
    "armstrong-numbers",
    "beer-song",
    "book-store",
    "circular-buffer",
    "clock",
    "decimal",
    "difference-of-squares",
    "doubly-linked-list",
    "forth",
    "gigasecond",
    "grains",
    "hello-world",
    "luhn",
    "macros",
    "minesweeper",
    "ocr-numbers",
    "paasio",
    "react",
    "reverse-string",
    "space-age",
    "sublist",
    "xorcism",
]
